### ISSUE TITLE
Password is required param, but does not error if unprovided

### ISSUE THREAD

**Issue by sosso** [whosonfirst/go-whosonfirst-pgis#1]
`bin/wof-pgis-index -mode=repo -pgis-user=myusername -verbose=true -strict=true -pgis-database=mydb -pgis-maxconns=1 ~/workspace/whosonfirst-data-venue-us-ca`

If password is left off, the dsn becomes 

`host=localhost port=5432 user=myusername password= dbname=mydb sslmode=disable` and it's unable to find the relation `whosonfirst`.  I think it's because the DSN becomes invalid, but pq just keeps chugging along.  Might be good to document.

**Comment by thisisaaronland** [comment]
Okay, the dsn shouldn't contain a `password=` config if it's empty when the db client is created. Thanks for the head up.
